# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true 	removing as per PR 

# Setup
title:               Musings
tagline:             'A thought journal'
description:         'This thought journal is maintained by <a href="https://github.com/grubdragon" target="_blank">@grubdragon</a>'
url:                 https://grubdragon.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Aryan Agal
  url:               https://grubdragon.github.io
  email:             aryanagal98@gmail.com
  github:            https://github.com/grubdragon
  
# Custom vars
version:             1.0.0
google_analytics:    'UA-116698723-1'

#added gem dependency
plugins:
    [jekyll-paginate, jekyll-feed]
